### ISSUE TITLE
Enforce code style

### ISSUE THREAD

**Issue by sldblog** [ministryofjustice/hmpps-architecture-as-code#11]
Everyone has different editors

Let's enforce a consistent style, so we don't auto-format over each other

**Comment by spikeheap** [comment]
So... we have EditorConfig to _promote_ consistency, but #28 (to enforce it) highlighted a bug in the GitHub Action available on the marketplace. 

We could
1. Fork that and publish a new version to get us moving
2. Write our own job to install/run EditorConfig 
3. Wait for a fix on that action
4. Add a readme telling contributors to use EditorConfig, and say that level of promotion is enough for now

I think I favour option 4, purely because it's the least effort, but I'm not particularly tied to anything 😀

**Comment by sldblog** [comment]
Looking at the [workflow syntax](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsuses) it looks like it's possible to use an action repository's commit SHA instead of a tag. I'll try it on the closed PR

**Comment by sldblog** [comment]
It worked 🎉 https://github.com/ministryofjustice/hmpps-architecture-as-code/runs/858135711

**Comment by sldblog** [comment]
Closed by #28.
